// <auto-generated />
using System;
using Ateliex.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ateliex.Data.Migrations
{
    [DbContext(typeof(AteliexDbContext))]
    [Migration("20220326154355_CreateCadastroSchema")]
    partial class CreateCadastroSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Ateliex.Areas.Cadastro.Models.Modelo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Codigo");

                    b.ToTable("Modelo", "cadastro");

                    b.HasData(
                        new
                        {
                            Codigo = "TM01",
                            Nome = "Tati Model 01"
                        },
                        new
                        {
                            Codigo = "TM02",
                            Nome = "Tati Model 02"
                        },
                        new
                        {
                            Codigo = "TM03",
                            Nome = "Tati Model 03"
                        },
                        new
                        {
                            Codigo = "TM04",
                            Nome = "Tati Model 04"
                        },
                        new
                        {
                            Codigo = "TM05",
                            Nome = "Tati Model 05"
                        },
                        new
                        {
                            Codigo = "TM06",
                            Nome = "Tati Model 06"
                        },
                        new
                        {
                            Codigo = "TM07",
                            Nome = "Tati Model 07"
                        },
                        new
                        {
                            Codigo = "TM08",
                            Nome = "Tati Model 08"
                        },
                        new
                        {
                            Codigo = "TM09",
                            Nome = "Tati Model 09"
                        },
                        new
                        {
                            Codigo = "TM10",
                            Nome = "Tati Model 10"
                        });
                });

            modelBuilder.Entity("Ateliex.Areas.Cadastro.Models.ModeloRecurso", b =>
                {
                    b.Property<string>("ModeloCodigo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Custo")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unidades")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModeloCodigo", "Id");

                    b.HasIndex("TipoId");

                    b.ToTable("ModeloRecurso", "cadastro");

                    b.HasData(
                        new
                        {
                            ModeloCodigo = "TM01",
                            Id = 1,
                            Custo = 20m,
                            Descricao = "Tecido",
                            TipoId = 1,
                            Unidades = 2
                        },
                        new
                        {
                            ModeloCodigo = "TM01",
                            Id = 2,
                            Custo = 4m,
                            Descricao = "Linha",
                            TipoId = 1,
                            Unidades = 20
                        },
                        new
                        {
                            ModeloCodigo = "TM01",
                            Id = 3,
                            Custo = 5m,
                            Descricao = "Outros",
                            TipoId = 1,
                            Unidades = 1
                        },
                        new
                        {
                            ModeloCodigo = "TM01",
                            Id = 4,
                            Custo = 100m,
                            Descricao = "Transporte",
                            TipoId = 2,
                            Unidades = 50
                        },
                        new
                        {
                            ModeloCodigo = "TM01",
                            Id = 5,
                            Custo = 5m,
                            Descricao = "Costureira",
                            TipoId = 3,
                            Unidades = 1
                        });
                });

            modelBuilder.Entity("Ateliex.Areas.Cadastro.Models.ModeloRecursoTipo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("ModeloRecursoTipo", "cadastro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Material"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Transporte"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Humano"
                        });
                });

            modelBuilder.Entity("Ateliex.Areas.Cadastro.Models.ModeloRecurso", b =>
                {
                    b.HasOne("Ateliex.Areas.Cadastro.Models.Modelo", "Modelo")
                        .WithMany("Recursos")
                        .HasForeignKey("ModeloCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ateliex.Areas.Cadastro.Models.ModeloRecursoTipo", "Tipo")
                        .WithMany("Recursos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Ateliex.Areas.Cadastro.Models.Modelo", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Ateliex.Areas.Cadastro.Models.ModeloRecursoTipo", b =>
                {
                    b.Navigation("Recursos");
                });
#pragma warning restore 612, 618
        }
    }
}
